### ISSUE TITLE
ct-ng and toolchain should be separate packages

### ISSUE THREAD

**Issue by mithro** [antmicro/conda-toolchains#4]
The crosstool-ng package should be separate from the package which *uses* crosstool-ng.

See example of the crosstool-ng package at;
 * https://anaconda.org/anaconda/crosstool-ng/files
 * https://github.com/conda-forge/ctng-compiler-activation-feedstock

**Comment by PiotrZierhoffer** [comment]
This is already done - our crosstool-ng is available on https://anaconda.org/antmicro/crosstool-ng
